tnt:
  power: 10           #how many TNTs
  cooldown: 20        #in ticks; 20 ticks = 1 s

chance:
  same_chance: 0.05   #set to false if you want different chances of blowing up for different colors or between 0 and 1 to set equal chance for all colors
  colors:
    - 0.05 #white
    - 0.05 #orange
    - 0.05 #magenta
    - 0.05 #light_blue
    - 0.05 #yellow
    - 0.05 #lime
    - 0.05 #pink
    - 0.05 #gray
    - 0.05 #light_gray
    - 0.05 #cyan
    - 0.05 #purple
    - 0.05 #blue
    - 0.05 #brown
    - 0.05 #green
    - 0.05 #red
    - 0.05 #black
